server:
  port: 8081

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: hospital.management.system0@gmail.com
    password: gwylhxbchifitmvk
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:https://164.92.206.217:8761/eureka/}
    instance:
      preferIpAddress: true