server:
  port: 8083

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: smtp.google.com
    port: 589
    username: jahonovjavohir0@gmail.com
    password: hxiiibxixgriyyac
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true


eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true