server:
  port: 8081

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: jamshidbekarimov@gmail.com
    password: gmarydooqvwjgwwz
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://134.209.20.129:8761/eureka/}
    instance:
      preferIpAddress: true